name: Create gobs

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    # env:
      # CI: true
      # EXT_BRANCH: codegen

    steps:
    - uses: actions/checkout@v1

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: generate gob files
      run: |
        cd gobify
        go run .

    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: gobs
        path: gobs
    