name: Generate GO Code

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CI: true
      EXT_BRANCH: codegen

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm install, build, and test
      run: |
        npm i -g pnpm
        pnpm install --frozen-lockfile
        npm run build --if-present

    - name: clone geocoder
      run: |
        git clone https://corporateanon:${{secrets.GITHUB_PAT}}@github.com/corporateanon/my1562geocoder.git pkg
        cd pkg
        git checkout -b $EXT_BRANCH || git checkout $EXT_BRANCH

    - name: codegen
      run: |
        npm run codegen

    - name: push geocoder
      run: |
        cd pkg
        if [ -z "$(git status --porcelain)" ]; then 
          echo "Nothing to commit"
        else 
          git config --global user.email "no"
          git config --global user.name "Github Action"
          git add .
          git commit -m 'build'
          git push -u origin $EXT_BRANCH
        fi
