name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm install, build, and test
      run: |
        npm i -g pnpm
        pnpm install --frozen-lockfile
        npm run build --if-present

    - name: clone geocoder
      run: |
        git clone git@github.com:corporateanon/my1562geocoder.git pkg

    - name: codegen
      run: |
        npm run codegen

    - name: push geocoder
      run: |
        cd pkg
        git add .
        git commit -m 'build'
        git push


      env:
        CI: true
